[package]
name = "webdcc"
version = "0.1.0"
edition = "2018"
description = "A simple web-based model train controller"
homepage = "webdcc.com"
repository = "https://github.com/Eelviny/webdcc"
license = "GPL-3.0-or-later"
license-file = "LICENSE"
publish = false

[dependencies]
yaml-rust = "0.4.5"